---
# Changed to Centos 6 due to issues installing npm using through yum on
# Centos 7 at time of writing.

- hosts: nodejs
  become: yes

# Default vars files could be overwritten by stipulating a var file or
# writing them explicitly here.

  pre_tasks:
    - name: Install Remi repo.
      yum:
        name: "http://rpms.remirepo.net/enterprise/remi-release-6.rpm"
        state: present

    - name: Import Remi GPG key.
      rpm_key:
        key: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"
        state: present
    - name: Install EPEL repo.
      yum: name=epel-release state=present

    - name: Install selinux-python.
      yum: name=libselinux-python state=present

    - name: Ensure firewall is stopped.
      service: name=iptables state=stopped

  roles:
    - nodejs

  tasks:
    - name: Ensure Node.js app folder exists.
      file: "path={{ node_apps_location }} state=directory"

    - name: Copy example Node.js app to server.
      copy: "src=app/{{ item }} dest={{ node_apps_location }}"
      with_items:
        - app.js
        - package.json

    - name: Install app dependencies.
      npm: path={{ node_apps_location }}

    - name: Check list of running Node.js apps.
      command: forever list
      register: forever_list
      changed_when: false

    - name: Start example Node.js app.
      command: "forever start {{ node_apps_location }}/app.js"
      when: "forever_list.stdout.find('{{ node_apps_location }}/app.js') == -1"
