---
- name: Install nodejs and all its dependencies.
  yum: name=npm enablerepo=epel-testing state=present enablerepo=epel

- name: Install forever module.
  npm: name=forever global=yes state=present
